name: Deploy to Crema Amazon ECS

# It will execute only When the branch name is main and crema-backend code is changed.
# Also when PR review requested or the label crema is registered.
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manually_trigger:
        description: 'Manually Trigger the Github Actions'
        type: boolean
        required: true

jobs:
  prepare:
    name: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
