name: Deploy to Crema Amazon ECS

# It will execute only When the branch name is main and crema-backend code is changed.
# Also when PR review requested or the label crema is registered.
on:
  push:
    branches:
      - main
    paths:
      - 'apps/crema-backend/**'
      - 'libs/**'
  pull_request:
    types:
      - labeled
    paths:
      - 'apps/crema-backend/**'
      - 'libs/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: false
        default: 'dev'
        options:
          - dev
          - stage
          - prod

jobs:
  crema-run:
    if: ${{ github.event.label.name == 'crema' }} && ${{ github.ref == 'refs/heads/main' }}
    name: crema-run
    runs-on: ubuntu-latest
    steps:
      # This step fetches code from github repository.
      - name: checkout-code
        uses: actions/checkout@v2

      # This step gets the hash from the commit and uses it for the docker image tag.
      - name: crema cat
        run: cat apps/crema-backend/test.json

      - name: libs cat
        run: cat libs/test.json