name: crema

on:
  push:
    branches:
      - main
    paths:
      - 'apps/crema-backend/**'
  pull_request:
    types:
      - labeled


jobs:
  deploy:
    if: ${{ github.event.label.name == 'crema' }} || ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event_name }}
          echo ${{ github.head_ref }}