on:
  workflow_call:
    secrets:
      SLACK_MENTION_WEBHOOK_URL: 
        required: true
  issue_comment:
    types: [created, edited]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@latest
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_MENTION_WEBHOOK_URL }}
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          configuration-path: https://github.com/HyunnSangCho/workflow-test/blob/main/.github/mention-to-slack.yml
