# on:
#   workflow_call:
on:
  issue_comment:
    types: [created]


jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@latest
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_MENTION_WEBHOOK_URL }}  # 호출할 때 정의된 비밀의 이름을 사용합니다.
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          configuration-path: .github/mention-to-slack.yml
