on:
  workflow_call:
    inputs:
      run-id:
        required: true
        type: string
      # 필요한 추가 입력들을 여기 정의할 수 있습니다.

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@latest
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.slack-webhook-url }} # 입력으로부터 받아온 값
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          bot-name: "Send Mention from jelatodev/pesca-issue"
          run-id: ${{ inputs.run-id }} # 입력으로부터 받아온 run-id
          configuration-path: .github/mention-to-slack.yml
