on:
  issue_comment:
    types: [created]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@latest
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_MENTION_WEBHOOK_URL }}
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          bot-name: "Send Mention from jelatodev/pesca-issue"
          run-id: ${{ github.run_id }}
          configuration-path: .github/mention-to-slack.yml
          
