on:
  workflow_call:
    inputs:
      slack-webhook-url:
        required: true
        type: string
        
jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@latest
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ inputs.slack-webhook-url }}
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          configuration-path: .github/mention-to-slack.yml
