name: Deploy to Pesca Amazon ECS

# It will execute only When the branch name is main and pesca-backend code is changed.
# Also when PR review requested or the label pesca is registered.
on:
  push:
    branches:
      - main
    paths:
      - 'apps/pesca-backend/**'
  pull_request:
    types:
      - labeled
    paths:
      - 'apps/pesca-backend/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: false
        default: 'dev'
        options:
          - dev
          - stage
          - prod

jobs:
  pesca-run:
    if: ${{ github.event.label.name == 'pesca' }} && ${{ github.ref == 'refs/heads/main' }}
    name: pesca-run
    runs-on: ubuntu-latest
    steps:
      # This step fetches code from github repository.
      - name: checkout-code
        uses: actions/checkout@v2

      - name: pesca cat
        run: cat apps/pesca-backend/test.json