name: pesca

on:
  push:
    branches:
      - main
    paths:
      - 'apps/pesca-backend/**'
  pull_request:
    types:
      - labeled


jobs:
  deploy:
    if: ${{ github.event.label.name == 'pesca' }} || ${{ github.head_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event_name }}
          echo ${{ github.head_ref }}