name: test

on:
  push:
    branches:
      - main
    paths:
      - 'apps/pesca-backend/**'
  pull_request:
    types:
      - labeled


jobs:
  deploy:
    if: ${{ github.event.label.name == 'pesca' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event_name }}
          echo ${{ github.head_ref }}